name: handleIssues
on:
    issues:
        types: [opened, edited, milestoned]
jobs:
    output_input:
        runs-on: ubuntu-latest
        steps:
            - name: output the issue infroamtion
              run: echo "${{toJson(github.event)}}"