name: test_project
on: [push]
jobs:
    Unit_testing:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: Install Node js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install  dependecies
              run: npm ci
            - name: run test
              run: npm test
    deploy:
        needs: Unit_testing
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: Install Node js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install  dependecies
              run: npm ci
            - name: run Build
              run: npm run build
            - name: Upload Artificat
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: |
                    dist
                    package.json
    deployProject:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get the build artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist-files
            - name: deploy
              run: echo "deploying ....."